package com.pervasive07;

/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'SerialMsg'
 * message type.
 */

public class SerialMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 13;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 11;

    /** Create a new SerialMsg of size 13. */
    public SerialMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new SerialMsg of the given data_length. */
    public SerialMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialMsg with the given data_length
     * and base offset.
     */
    public SerialMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialMsg using the given byte array
     * as backing store.
     */
    public SerialMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public SerialMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public SerialMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialMsg embedded in the given message
     * at the given base offset.
     */
    public SerialMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialMsg embedded in the given message
     * at the given base offset and length.
     */
    public SerialMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <SerialMsg> \n";
      try {
        s += "  [header=0x"+Long.toHexString(get_header())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [srcid=0x"+Long.toHexString(get_srcid())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [relayid=0x"+Long.toHexString(get_relayid())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [sync_p=0x"+Long.toHexString(get_sync_p())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [temperature=0x"+Long.toHexString(get_temperature())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [light=0x"+Long.toHexString(get_light())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [fire=0x"+Long.toHexString(get_fire())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [rssi=0x"+Long.toHexString(get_rssi())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: header
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'header' is signed (false).
     */
    public static boolean isSigned_header() {
        return false;
    }

    /**
     * Return whether the field 'header' is an array (false).
     */
    public static boolean isArray_header() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'header'
     */
    public static int offset_header() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'header'
     */
    public static int offsetBits_header() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'header'
     */
    public short get_header() {
        return (short)getUIntBEElement(offsetBits_header(), 8);
    }

    /**
     * Set the value of the field 'header'
     */
    public void set_header(short value) {
        setUIntBEElement(offsetBits_header(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'header'
     */
    public static int size_header() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'header'
     */
    public static int sizeBits_header() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: srcid
    //   Field type: int, unsigned
    //   Offset (bits): 8
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'srcid' is signed (false).
     */
    public static boolean isSigned_srcid() {
        return false;
    }

    /**
     * Return whether the field 'srcid' is an array (false).
     */
    public static boolean isArray_srcid() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'srcid'
     */
    public static int offset_srcid() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'srcid'
     */
    public static int offsetBits_srcid() {
        return 8;
    }

    /**
     * Return the value (as a int) of the field 'srcid'
     */
    public int get_srcid() {
        return (int)getUIntBEElement(offsetBits_srcid(), 16);
    }

    /**
     * Set the value of the field 'srcid'
     */
    public void set_srcid(int value) {
        setUIntBEElement(offsetBits_srcid(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'srcid'
     */
    public static int size_srcid() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'srcid'
     */
    public static int sizeBits_srcid() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: relayid
    //   Field type: int, unsigned
    //   Offset (bits): 24
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'relayid' is signed (false).
     */
    public static boolean isSigned_relayid() {
        return false;
    }

    /**
     * Return whether the field 'relayid' is an array (false).
     */
    public static boolean isArray_relayid() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'relayid'
     */
    public static int offset_relayid() {
        return (24 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'relayid'
     */
    public static int offsetBits_relayid() {
        return 24;
    }

    /**
     * Return the value (as a int) of the field 'relayid'
     */
    public int get_relayid() {
        return (int)getUIntBEElement(offsetBits_relayid(), 16);
    }

    /**
     * Set the value of the field 'relayid'
     */
    public void set_relayid(int value) {
        setUIntBEElement(offsetBits_relayid(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'relayid'
     */
    public static int size_relayid() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'relayid'
     */
    public static int sizeBits_relayid() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sync_p
    //   Field type: int, unsigned
    //   Offset (bits): 40
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sync_p' is signed (false).
     */
    public static boolean isSigned_sync_p() {
        return false;
    }

    /**
     * Return whether the field 'sync_p' is an array (false).
     */
    public static boolean isArray_sync_p() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sync_p'
     */
    public static int offset_sync_p() {
        return (40 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sync_p'
     */
    public static int offsetBits_sync_p() {
        return 40;
    }

    /**
     * Return the value (as a int) of the field 'sync_p'
     */
    public int get_sync_p() {
        return (int)getUIntBEElement(offsetBits_sync_p(), 16);
    }

    /**
     * Set the value of the field 'sync_p'
     */
    public void set_sync_p(int value) {
        setUIntBEElement(offsetBits_sync_p(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'sync_p'
     */
    public static int size_sync_p() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sync_p'
     */
    public static int sizeBits_sync_p() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: temperature
    //   Field type: int, unsigned
    //   Offset (bits): 56
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'temperature' is signed (false).
     */
    public static boolean isSigned_temperature() {
        return false;
    }

    /**
     * Return whether the field 'temperature' is an array (false).
     */
    public static boolean isArray_temperature() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'temperature'
     */
    public static int offset_temperature() {
        return (56 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'temperature'
     */
    public static int offsetBits_temperature() {
        return 56;
    }

    /**
     * Return the value (as a int) of the field 'temperature'
     */
    public int get_temperature() {
        return (int)getUIntBEElement(offsetBits_temperature(), 16);
    }

    /**
     * Set the value of the field 'temperature'
     */
    public void set_temperature(int value) {
        setUIntBEElement(offsetBits_temperature(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'temperature'
     */
    public static int size_temperature() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'temperature'
     */
    public static int sizeBits_temperature() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: light
    //   Field type: int, unsigned
    //   Offset (bits): 72
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'light' is signed (false).
     */
    public static boolean isSigned_light() {
        return false;
    }

    /**
     * Return whether the field 'light' is an array (false).
     */
    public static boolean isArray_light() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'light'
     */
    public static int offset_light() {
        return (72 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'light'
     */
    public static int offsetBits_light() {
        return 72;
    }

    /**
     * Return the value (as a int) of the field 'light'
     */
    public int get_light() {
        return (int)getUIntBEElement(offsetBits_light(), 16);
    }

    /**
     * Set the value of the field 'light'
     */
    public void set_light(int value) {
        setUIntBEElement(offsetBits_light(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'light'
     */
    public static int size_light() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'light'
     */
    public static int sizeBits_light() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: fire
    //   Field type: byte, unsigned
    //   Offset (bits): 88
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'fire' is signed (false).
     */
    public static boolean isSigned_fire() {
        return false;
    }

    /**
     * Return whether the field 'fire' is an array (false).
     */
    public static boolean isArray_fire() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'fire'
     */
    public static int offset_fire() {
        return (88 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'fire'
     */
    public static int offsetBits_fire() {
        return 88;
    }

    /**
     * Return the value (as a byte) of the field 'fire'
     */
    public byte get_fire() {
        return (byte)getSIntBEElement(offsetBits_fire(), 8);
    }

    /**
     * Set the value of the field 'fire'
     */
    public void set_fire(byte value) {
        setSIntBEElement(offsetBits_fire(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'fire'
     */
    public static int size_fire() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'fire'
     */
    public static int sizeBits_fire() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: rssi
    //   Field type: short, unsigned
    //   Offset (bits): 96
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'rssi' is signed (false).
     */
    public static boolean isSigned_rssi() {
        return false;
    }

    /**
     * Return whether the field 'rssi' is an array (false).
     */
    public static boolean isArray_rssi() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'rssi'
     */
    public static int offset_rssi() {
        return (96 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'rssi'
     */
    public static int offsetBits_rssi() {
        return 96;
    }

    /**
     * Return the value (as a short) of the field 'rssi'
     */
    public short get_rssi() {
        return (short)getUIntBEElement(offsetBits_rssi(), 8);
    }

    /**
     * Set the value of the field 'rssi'
     */
    public void set_rssi(short value) {
        setUIntBEElement(offsetBits_rssi(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'rssi'
     */
    public static int size_rssi() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'rssi'
     */
    public static int sizeBits_rssi() {
        return 8;
    }

}
